name: rl_course

dependencies:
  - python=3.8.2
  - numpy=1.18*
  - matplotlib=3.1*
  - seaborn=0.10.1
  - tqdm=4.46.0
  - scipy=1.4*
  - jupyter=1.0*
  - ipykernel=5.1.4
  - pip=20.0*

  - pip:
    - pylint
    - pep8
    - autopep8
